### ISSUE TITLE
Ordering a bit hard

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/VitaDB-Downloader#1]
Please allow left and right buttons to be page up and down 

Press allow for the scrollbar to be touchable.

If you order by say Ascending and then select the first row, then change to Descending you'll be at the bottom of the list and there's no way to get back so you will have to scroll forever or close the app 

Thanks

**Comment by Rinnegatamante** [comment]
There is already a Top shortcut as explained in the release post: O + Left

**Comment by Sarkie** [comment]
@Rinnegatamante Apologies, I didn't read it like that, maybe an ingame ui text where the sorting mode is?

**Comment by Rinnegatamante** [comment]
All those suggestions had been addressed in v.1.1.
You can now page up/down with left/right.
You can directly move scrollbar with left analog.
Changing sorting won't randomly move around the cursor.

**Comment by Sarkie** [comment]
Thanks @Rinnegatamante
