### ISSUE TITLE
Crash while parsing apps list

### ISSUE THREAD

**Issue by EQQx110** [Rinnegatamante/VitaDB-Downloader#11]
I just installed the app and it crashes a second after the “parsing apps list” text appears on screen.

I’ve checked if I have libshacccg.suprx installed, and although it is present in the ur0:/data folder and I remember installing it, I’m not sure if it has been disabled somehow, as quite some time has passed from when I installed it (months ago I had problems I with the micro SD I think, apps disappeared and the theme got removed and other annoying shit, btw if you know why that happened I would be glad if you tell me and how to prevent it).

Anyway if I installed it, it is because I needed it to play or use certain games and apps, and since I can still use everything without crashes, I don’t think libshacccg.suprx is the problem, but I could be wrong nonetheless.

Sorry for bad english.

**Comment by Rinnegatamante** [comment]
Does Nightly crash as well? https://github.com/Rinnegatamante/VitaDB-Downloader/releases/tag/Nightly

**Comment by EQQx110** [comment]
A week later I picked up the Vita and retried using the app and the problem fixed itself, IDK what happened, thank you anyway
