### ISSUE TITLE
Translation confusion

### ISSUE THREAD

**Issue by wuchenkang** [Rinnegatamante/VitaDB-Downloader#13]
I tried to do some thranslations for this app. But after I changed the font file and replaced the original text with translated u8 strings, as mentioned in imgui guide, I only got ??? instead of translated text. I wonder whether the ported imgui library support utf-8 strings or I missed some necessary steps.

**Comment by Rinnegatamante** [comment]
You need to add proper range for whatever language you need https://github.com/Rinnegatamante/yoyoloader_vita/blob/main/selector/main.cpp#L1567-L1576
