### ISSUE TITLE
crash while "downloading app icons"

### ISSUE THREAD

**Issue by moo182** [Rinnegatamante/VitaDB-Downloader#17]
was working up until v1.4
now it keeps crashing/rebooting when "downloading app icons"

tried reinstalling directly from the git
also deleted the ux0:data/VitaDB folder before trying again

problem remains

happy to provide more deets if it can provide a fix

**Comment by Rinnegatamante** [comment]
Manually update to v.1.5 (or Nightly) and see if the issue is still there.

**Comment by moo182** [comment]
tried downloading the vpk from the git, no change

**Comment by Rinnegatamante** [comment]
Try to delete icons folder and icons.db file from ux0:data/VitaDB.

**Comment by moo182** [comment]
there's an empty icons folder and no icons.db
i deleted the folder and tried again, no change.

**Comment by Rinnegatamante** [comment]
Can you upload a coredump took with this build? [VitaDB.zip](https://github.com/Rinnegatamante/VitaDB-Downloader/files/9594062/VitaDB.zip)

**Comment by moo182** [comment]
did a fresh install with the uploaded build. no coredump was produced even though the system rebooted.

**Comment by Rinnegatamante** [comment]
Don't know, this feels like your system is quite messed up honestly.

**Comment by moo182** [comment]
I disagree, my system isn't messed up.
this is the first hiccup since softmodding in 2019.
it runs emulators, ports and fan translated games, in addition to ripped titles (vita and psp)
however I do agree there is something disagreeable happening in this instance.
thank you anyway for your time, hopefully this stays up should anyone else have the same problem.

**Comment by Rinnegatamante** [comment]
Did you happen to jailbreak your console with MLTHaku?

**Comment by moo182** [comment]
downgraded to 3.60 using modoru
softmodded using HENkaku
YAMT for storage

**Comment by FeverFish** [comment]
Had the same problem. I restarted my vita, then opening the app asked for a wi-fi login. Logged in and proceeded no problem. I am guessing if it does not detect a wi-fi connection, it causes this crash? Perhaps verify if connected before entering the app?

**Comment by moo182** [comment]
system is connected to wifi

**Comment by cmcginty** [comment]
Same error. My internet settings were not correct. Verify that internet connection tests works, and DNS settings are correct. Also try opening the web browser and loading some pages.
