### ISSUE TITLE
Ignore feature

### ISSUE THREAD

**Issue by mightysashiman** [Rinnegatamante/VitaDB-Downloader#18]
Please add a way to toggle a "ignore" flag on a vitadb entry listed. I suggest the following UX:

- vita entry in the main pane appears by default (not ignored).
- A specific button or menu action enables user to set ignore flag on selected/highlighted entry
- In which case entry is hidden from main pain, appears in "ignored" pane.
- Similar action is possible from the "ignored pane" to reverse action.

Example of usecase: sonic vita has to be manually compiled and installed to access encore mode (I HAVE PAID FOR IT). VitaDB Downloader 1.5 seems to detect my manually compiled build (based on 1.0.2 source) as older than the 1.0.2 version available from vitaDB repo.

**Comment by Rinnegatamante** [comment]
There's no free to use key and such a feature feels just pointless.
