### ISSUE TITLE
Move category filtering and searching to a separate window

### ISSUE THREAD

**Issue by PookaMustard** [Rinnegatamante/VitaDB-Downloader#2]
I realize as of 1.1 that there is now an easier shortcut to the very top of the screen where the aforementioned items are, but a pop-up menu or a separate window would bring more benefits, namely not losing scroll position when considering what to search (so if you change your mind you could continue instead of starting over).

**Comment by Rinnegatamante** [comment]
You can start a search by pressing Triangle as of v.1.2. I don't plan to clogger the gui with extra windows.
