### ISSUE TITLE
Crashes in first run if flight mode is on

### ISSUE THREAD

**Issue by dekay** [Rinnegatamante/VitaDB-Downloader#21]
I installed VitaDB Downloader v.1.5 from a VPK file and data file downloaded [from here](https://vitadb.rinnegatamante.it/#/info/877).  Tried to run it and it crashed as soon as it tried to download stuff.  Tried a couple more times with the same result.  Then noticed that I had flight mode on.  Turned that off and and it downloaded all the png and other files successfully.

The .tmp file generated in ux0:/data says "Data abort exception", Thread name "VITADBBDLD", and cause "0x00030004"

A check for this with an appropriate error message is probably a good idea.

**Comment by v-atamanenko** [comment]
@dekay this application even has the word *downloader* in its title, which 100% implies that it needs internet connectivity to work. So launching it with flight mode on is something like turning on a PC with power cord not plugged in :)

But I'd maybe agree that for a wider range of internet connection-related issues (DNS issues, unreachable IPs, et cetera), `ping 8.8.8.8` on startup with an error message in case of failure seems to be a good idea.

**Comment by dekay** [comment]
@v-atamanenko Right.  But to follow your analogy, my PC doesn't blow up if I try to turn it on without the power cord plugged in  :-)

In my case, I had flight mode turned on a long time ago and that didn't come to mind right away.  All I had was the app crash on me a couple times.  A simple check and a message to connect the dots would certainly be nice to have.

**Comment by Rinnegatamante** [comment]
Done with https://github.com/Rinnegatamante/VitaDB-Downloader/commit/027b48b2fa5dcdc8e70ab7c16e238fcb389199da
