### ISSUE TITLE
Issues with "Outdated Apps" after 1.6 update

### ISSUE THREAD

**Issue by Levine91** [Rinnegatamante/VitaDB-Downloader#23]
I just updated to 1.6 this morning, the app auto-updated itself.
After doing such I went to sort by my "Outdated Apps" (which I regularly do) and now a number of apps I've never installed before are showing up as outdated. 
Even more curiously, and hopefully this is helpful, when I look at the changelog on those incorrect apps, they are each listed as "First Release"

These are the following apps that appear:
- Fractal3D v.1.0
- Super Pop-up Blocker 2000 Draft
- Ronister Adventure Demo v.1.1
- Brico Laika v.1.0
- Deadly Hallows v.1.0
- Bot-R v.1.0
- The Lost Catacomb v.1.0
- The Enchanted Forest v.1.1
- FryingMaster v.2.1
- V-Cube v.1.0

Now in addition to those apps I've never installed before, I'm also showing some apps that I DO have installed are "outdated" but showing their earliest incarnation (or current version I have installed) as the update option.

Examples: 
- devilutionX v.0.5.0 Beta 1 
- Flash Light v.1.0
- Flop Rocket v.1.0

**Comment by Rinnegatamante** [comment]
That's cause of bad homebrews sharing titleid. Unfortunately not something that can be fixed from VitaDB Downloader side. Authors of those homebrews should release an updated that makes so that titleid doesn't clash with other homebrews https://vitadb.rinnegatamante.it/#/titleids
