### ISSUE TITLE
"Invalid sce header"

### ISSUE THREAD

**Issue by EpicLPer** [Rinnegatamante/VitaDB-Downloader#28]
(Sorry, initially sent without text cause phone)

When installing VitaDB and it goes to the SharkF00D install it errors out with "Invalid sce header (magic != sce)", can't find anything about this anywhere sadly. Does anyone happen to know a fix for this?

**Comment by Rinnegatamante** [comment]
What firmware do you have?

**Comment by EpicLPer** [comment]
Sorry for the immensely long wait time for my reply, life kind of... happened 🫠

Anyways, my Vita is on 3.60

**Comment by Rinnegatamante** [comment]
Closing this since unrealted to VitaDB Downloader (looks more like an issue with ShaRKF00D. Maybe you tried to launch it when Sony servers were offline? (Cause PSM Runtime is downloaded from its official download link)

**Comment by EpicLPer** [comment]
> Closing this since unrealted to VitaDB Downloader (looks more like an issue with ShaRKF00D. Maybe you tried to launch it when Sony servers were offline? (Cause PSM Runtime is downloaded from its official download link)

Yeah, it does seem like an issue with ShaRKF00D, tried again and it's still not working :(
