### ISSUE TITLE
Respect VPKs installed outside of VitaDB Downloader?

### ISSUE THREAD

**Issue by danielmmmm** [Rinnegatamante/VitaDB-Downloader#29]
VitaDB Downloader marks apps not in its DB as outdated, even though they aren't. This is problematic for apps that have to be installed manually to add game data, like Pony Island (https://github.com/hatoving/PonyIsland). But it is also problematic for apps that have nightly versions, like RetroArch (http://buildbot.libretro.com/nightly/playstation/vita/).

In these cases, VitaDB Downloader marks the installed apps as "outdated", even though they aren't. Worse, updating the apps will either install an older version (RetroArch), or it will replace the app with a blank version missing the data (Pony Island).

A particularly curious case is ScummVM, which VitaDB Downloader happily updates and downgrades indefinitely. **My installed v2.6.1 gets updated to the v2.7 nightly. Upon restarting VitaDB Downloader, ScummVM gets flagged as outdated. Updating ScummVM v2.7 will install v2.6.1 again. Upon restarting VitaDB Downloader, ScummVM gets flagged as outdated, and we start over at **.

I don't just want to complain, I'd like to come up with a solution as well. Unfortunately, I don't know enough about the Sony VPK format. As far as I am aware, some VPKs (param.sfo) contain no or wrong version information ... because the developer(s) don't care? When VPKs have to be compiled by the user (Pony Island), the checksum of the eboot will change and and it is probably impossible to collect these checksums in VitaDB.

Would it make sense to give users the ability to mark apps as "don't update" (maybe in blue font)? When the user tries to update such an app, VitaDB Downloader could show a warning and three options: Toggle "don't update" state, update, and chancel.

A more drastic approach would be to remove some apps from the DB, or display the app information without providing an install option. After all, a game like Pony Island cannot be made playable without using the original GitHub content.

**Comment by Rinnegatamante** [comment]
You're literally refering to apps that have more than an entry in VitaDB. If you keep installing first ScummVM v.2.6.1 and then ScummVB Buildbot, it will ofc keep swapping versions undefinitely. Version check is done via hash check which is the sole way to perform such kind of checks. Nightly in VitaDB don't offer a proper hash due to their nature.
![immagine](https://user-images.githubusercontent.com/9152710/212957476-7c41234c-b195-4b3f-8647-bc9540572705.png)

**Comment by danielmmmm** [comment]
Sorry, I did not intend to blame you for what's happening with ScummVM. (I actually read another comment, where you pointed out why some apps are problematic because they have more than an entry in VitaDB 😊)

While ScummVM may be an exception, I still think that a "don't update" flag would make sense. Alternatively, we (I) could ask developers like @hatoving to move data files to \ux0\data so that the app can be updated independently from its data. But there seem to be more than a handful of "problematic" apps, and older apps will probably never see a fix ever. And nightly versions don't work with the current implementation anyways.

**Comment by hatoving** [comment]
Just a note; I can't tell the game where to look for the files because, frankly, that's not possible with Unity (the engine it's running on).

**Comment by danielmmmm** [comment]
Too bad. But thanks for replying ... and unravelling yet another mystery 😁

**Comment by Rinnegatamante** [comment]
For Pony Island, only the eboot.bin is checked for hash which means it shouldn't have such issue.

**Comment by danielmmmm** [comment]
The eboot.bin gets patched as well when adding the data files for Pony Island.

**Comment by Rinnegatamante** [comment]
This should be now at least avoidable with the Tag as Updated feature added in v.1.8.
