### ISSUE TITLE
Add info about PSM 

### ISSUE THREAD

**Issue by SharpThunder** [Rinnegatamante/VitaDB-Downloader#3]
Hi!
I think there should be info about PSM in requirements.
Thanks for your work.

**Comment by Rinnegatamante** [comment]
PSM is not required

**Comment by SharpThunder** [comment]
I got error about libshacccg.suprx when i launched the app. After I installed it using this guide 
https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx
it is fixed.

**Comment by Rinnegatamante** [comment]
Welp, libshacccg.suprx is not PSM. (You can even fully uninstall PSM runtimes after extracting it). Btw i've added a note to the README.

**Comment by SharpThunder** [comment]
Sorry didn't know about that.
Thanks.
