### ISSUE TITLE
FEATURE_REQUEST: Quake Mods

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/VitaDB-Downloader#32]
Support the downloading of quake mods, as it runs very easily

Just needs a .cfg change to do the gamepads.

**Comment by Rinnegatamante** [comment]
...don't think I even need to comment this.

**Comment by Sarkie** [comment]
@Rinnegatamante  I've changed it to be more generic, so hopefully you understand what I'm trying to get at.

Thanks

**Comment by Rinnegatamante** [comment]
This has nothing to do with homebrews. I'm not gonna maintain a mods website for every single game in existence on Vita.

**Comment by Sarkie** [comment]
🙄 ok Rinn.
