### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by vamp-2000** [Rinnegatamante/VitaDB-Downloader#33]
The downloader gives me a notification for an update for VitaDB 1.7 every time I boot my system. When I click to download the update it says something along the lines of "failed to update" (which I assume is because its already installed). The notification persists and I'm not sure if there is a way to fix this on my end.

**Comment by vamp-2000** [comment]
I was able to fix the issue by updating it inside the application itself.

**Comment by Rinnegatamante** [comment]
That's likely cause you had nightly build. The hash check checks for latest stable version which will result different to nightly one.

**Comment by yeaguy** [comment]
I see this is closed but figured I'd share in case anyone else had the same issue.

I have the same issue with the notification to update periodically as well as at every boot up. However, when I run vitaDB it says it's running version 1.7 in the top left corner. Finding the application on the program says it's outdated and when I click to update on the live area menu it goes through the download process but fails to install.

Any ideas or thoughts would be much appreciated.

**Comment by Rinnegatamante** [comment]
That's because you have Nightly build likely. Just add VITADBDLD to daemon blacklist.
