### ISSUE TITLE
Apollo Save tool update

### ISSUE THREAD

**Issue by LittleTale** [Rinnegatamante/VitaDB-Downloader#34]
Vita keep asking me to download apollo save toll update everytime.
app is outdated in the database and after installing from VitaDB when you open apollo, it ask you to download newer version.

Is there a way to force stop notification for certain apps until the database get updated ?

Thanks a lot in advance.

**Comment by Rinnegatamante** [comment]
Check README on this repository for info on how to add applications in daemon blacklist.

**Comment by LittleTale** [comment]
Thanks you so much ! Tremendous work on this app !
You're amazing.
