### ISSUE TITLE
Reports itself as outdated (v1.7) and fails to update

### ISSUE THREAD

**Issue by Chudesnov** [Rinnegatamante/VitaDB-Downloader#38]
Firmware: 3.65 Henkaku Enso
VitaDB Downloader Version: 1.7 

Each time I reboot my Vita, a notification pops up saying update is available for a homebrew. Tapping it starts VitaDB Downloader v1.7, which downloads VitaDB Downloader v1.7, tries to install itself and fails.

expected result:
- 1.7 should not consider itself outdated when the latest version is still 1.7;
- self-updating, if needed, should work.

**Comment by Rinnegatamante** [comment]
Are you on nightly or stable 1.7?

**Comment by Chudesnov** [comment]
Screen title just says “VitaDB Downloader v1.7”, so I am not sure how to answer that, stable _probably_?

**Comment by Rinnegatamante** [comment]
What's the content of ux0:app/VITADBDLD/hash.vdb?

**Comment by Chudesnov** [comment]
@Rinnegatamante starts with 272ad6

**Comment by Rinnegatamante** [comment]
Seems to be incorrect indeed. I'll change version checking process in next release i guess.

**Comment by Rinnegatamante** [comment]
Should be fixed now and if happens again, v.1.8 introduced the "Tag as Updated" feature.
