### ISSUE TITLE
VitaDB Downloader reports homebrews as installed that aren't

### ISSUE THREAD

**Issue by Sergorov** [Rinnegatamante/VitaDB-Downloader#39]
As the title says, I see in the list homebrews that show as 'outdated' which are not installed. Some of them never were, at least to my knowledge. As I'm not sure how installed apps are detected I can't say what the source of that error could be. I have installed and uninstalled plenty of things over two years since I've had my Vita, potentially some remnants of this linger somewhere. But it's actually quite a few. Way too many to just blame my bad memory for all of them. 
The list:
Fractal3D v.1.0
Super Pop-up Blocker 2000 Draft
Ronister Adventure Demo v.1.1
Brico Laika v.1.0
V-Cube v.1.0
Deadly Hallows v.1.0
Bot-R v.1.0
Flappy Bird Vita v.1.0
The Lost Catacomb v.1.0
The enchanted Forest v.1.1
FryingMaster v.2.1
As I said, I'm 99% sure I had none of those ever installed. They are nowhere to be found as bubbles, and as far as I could see, there are no files in /data for them either. Any advice would be appreciated.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/VitaDB-Downloader/issues/23
