### ISSUE TITLE
Downloads VPK but doesn’t install

### ISSUE THREAD

**Issue by GlitchedDot** [Rinnegatamante/VitaDB-Downloader#4]
I tried installing a couple things but after downloading and extracting, it doesn’t install said apps and said apps do not appear in the live area and nowhere in the app folder. The data downloads and extracts fine but the VPKs do not install.

**Comment by Rinnegatamante** [comment]
What plugins do you have installed? I can't reproduce this issue so it must be somehow your setup. Also do you have enough free storage for the vpk install? (You need approx. twice the reported size in the app)

**Comment by GlitchedDot** [comment]
I got a 512GB microSD in my Vita so, space is not a concern. Plug-ins? 



# VBANIM
*NPXS10015
ur0:tai/vbanim.suprx
ur0:tai/henkaku.suprx
ur0:tai/sysident.suprx

*KERNEL
ur0:tai/storagemgr.skprx
ur0:tai/0syscall6.skprx
ur0:tai/nonpdrm_un.skprx
ur0:tai/repatch_ex.skprx
#ur0:tai/usbmc.skprx
ur0:tai/itls.skprx
ur0:tai/nopsmdrm.skprx
ux0:app/pspemucfw/sce_module/adrenaline_kernel.skprx
ur0:tai/cpuaffinitychanger.skprx
ur0:tai/lolita500.skprx
ur0:tai/capunlocker.skprx
ur0:tai/reauth.skprx
ur0:tai/kubridge.skprx
ur0:tai/sysident.skprx
ur0:tai/psvshellplus_kernel.skprx
ur0:tai/BetterTrackPlug.skprx
ur0:tai/ioplus.skprx

# ITLS
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
ur0:tai/PSVshellPlus_Shell.suprx
ur0:tai/pngshot.suprx
ur0:tai/quietshot.suprx
ur0:tai/shellbat.suprx
ur0:tai/TrophyShot.suprx
ur0:tai/quickmenuplus.suprx
ur0:tai/USBDisable.suprx
ur0:tai/fruitpeel.suprx
# this is for modifying the version string
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
ur0:tai/sysident.suprx
*NPXS10095
ur0:tai/quietshot.suprx
*NPXS10036
ur0:tai/reScreeny.suprx
*ALL
ur0:tai/VitaGrafix.suprx

**Comment by Rinnegatamante** [comment]
Did you happen to hack your console using MLThaku?

**Comment by GlitchedDot** [comment]
No, I used the Vita hack guide to install Henkaku Enso on 3.60.

**Comment by Rinnegatamante** [comment]
Can you reach up Vita Nuova server? https://discord.gg/PyCaBx9
Want to tackle this down and it's easier to actually solve it "live" rather than via GitHub Issues.

**Comment by GlitchedDot** [comment]
Sure, one moment

**Comment by GlitchedDot** [comment]
Alright, go to the VitaDB channel right?

**Comment by Rinnegatamante** [comment]
Yep

**Comment by Rinnegatamante** [comment]
If anyone else get this issue, issue was caused by attempting to install a VitaDB Downloader update with VitaDB Downloader itself prior to v.1.2. To solve it just delete the folder ux0:data/VitaDB/vpk.
