### ISSUE TITLE
VitaDB Downloadeer doesnt work anymore

### ISSUE THREAD

**Issue by retromookie** [Rinnegatamante/VitaDB-Downloader#40]
An error has occured in the following application. 
(C2-12828-1)
I cant open the downloader or open apps which i downloaded from it either. Pls help me to fix this issue.

![IMG_8693](https://github.com/Rinnegatamante/VitaDB-Downloader/assets/136069248/e78a7d09-8c65-48a1-9ef6-816394ea6835)

**Comment by Zhabok** [comment]
Same happened to me right now, opened Sharkfood and let it do what it does, then everything worked

**Comment by retromookie** [comment]
Thx it worked :D
