### ISSUE TITLE
app crashes on first time load v.1.7

### ISSUE THREAD

**Issue by learningcscience** [Rinnegatamante/VitaDB-Downloader#41]
hello

i dont know where to ask question. I just downloaded v.1.7 vpk and tried to install using vitashell. It installs but when i launch the app for the first time it gives an error "an error has occured" and it exits. could there be any additional files i need to download and install? i appreciate your help. thanks!

**Comment by Rinnegatamante** [comment]
No additional file is required.

**Comment by learningcscience** [comment]
thank you but could you please tell me why does it crash. i am using ps vita slim. I have also tried installing version 1.6. both crashes when starting.

**Comment by Rinnegatamante** [comment]
What firmware? How did you install Henkaku? What plugins do you have active?

**Comment by learningcscience** [comment]
thank you very much for replying. i am using 3.65 henkaku. could you please tell me what plugins i will need in order to run this app?

**Comment by Rinnegatamante** [comment]
You answered one out of three questions i put.

**Comment by learningcscience** [comment]
sorry i dont know how henkaku was installed. i bought second hand ps vita slim that had already henkaku. can you tell me how to check which plugins are active? Thanks!

**Comment by Rinnegatamante** [comment]
Depending on where you have plugins, it's either based on what you have in ux0:tai/config.txt or ur0:tai/config.txt

**Comment by learningcscience** [comment]
thank you for your attention. i think ill just download the app i need from the vitadb site.
