### ISSUE TITLE
Tag as updated?

### ISSUE THREAD

**Issue by pmsobrado** [Rinnegatamante/VitaDB-Downloader#43]
I just saw this option on 1.8 release. I understand this tagging is lost when the app is closed, right?

I haven't found any info on this, or another way to ask, so sorry if this is not the place.

**Comment by Rinnegatamante** [comment]
No, it's not lost.

**Comment by pmsobrado** [comment]
> No, it's not lost.

And how to restore its outdated status?

**Comment by Rinnegatamante** [comment]
Either uninstall and reinstall outdated version or delete ux0:app/TITLEID/hash.vdb where TITLEID is the titleid of the app.

**Comment by pmsobrado** [comment]
Thanks.
