### ISSUE TITLE
Tag as updated not working when multiple HB with same titleid

### ISSUE THREAD

**Issue by pmsobrado** [Rinnegatamante/VitaDB-Downloader#44]
I just noticed this behaviour. I have an updated version of PKGj and tagging it as updated seems to do the trick, but for example for VITAident and VITAident GUI, if tagging one as updated, the other one shows as outdated, and tagging that other one makes the first one shows as outdated again.

**Comment by Rinnegatamante** [comment]
That's something that can't be solved from VitaDB Downloader side. The Tag as Updated simply forces md5 hash to match with VitaDB one but when titleid is shared across different homebrews, there are multiple hashes to check against.

**Comment by pmsobrado** [comment]
Understood, thanks!
