### ISSUE TITLE
[bug] Fails to start when launched from QuickLaunch

### ISSUE THREAD

**Issue by danielmmmm** [Rinnegatamante/VitaDB-Downloader#45]
When VitaDB Downloader is launched from QuickLaunch, it opens a window saying "This homebrew is already up to date. (OK)". Upon touching the "OK" button, the app just quits.

The app is executed from "whatsnew.xml" with "psgm:play?titleid=VITADBDLD".

**Comment by Rinnegatamante** [comment]
That's a problem in how QuickLaunch works if anything.

**Comment by danielmmmm** [comment]
Sure, but ... no one can change QL ... so ... that's why i opened a bug report for VitaDB Downloader instead.

**Comment by danielmmmm** [comment]
Btw., do you really think this bug report is invalid, or do you just not have the time to fix it? I mean, not having the time to fix something you don't even get money for is a perfectly fine reason. Otherwise, why close this issue and shutting down any discussion?
