### ISSUE TITLE
VitaDB Hangs at Startup - "Downloading apps icons"

### ISSUE THREAD

**Issue by milksama** [Rinnegatamante/VitaDB-Downloader#49]
I had a previous version of VitaDB installed, but was getting this on startup:
![IMG_6582](https://github.com/Rinnegatamante/VitaDB-Downloader/assets/3102550/22bad46f-5a8b-4746-aca6-30c7a34257b2)

I tried removing that and throwing on the new build you published today, but no change. Is there any logging (or a way to turn it on)?

Thanks for any advice you can offer and of course for all your efforts in keeping the PSVita alive!

-Mike

**Comment by milksama** [comment]
Thanks for your quick reply!

I assure you I'd tried several things before opening this issue -- also, my first internet connection was through a 2400 baud modem, so I have an abundance of patience! In any event, I've just now let my PSVita sit for about 30 minutes attempting to download the icons, but still no indication of progress.

I'll hopefully have some time this weekend to troubleshoot further and will follow-up with any findings here.

**Comment by Rinnegatamante** [comment]
Try to fully clear VitaDB folder in ux0:data, replace content with Data Files download on VitaDB, and re-run the app.

**Comment by Jorengarenar** [comment]
I have the same issue. Tried using data files from VitaDB, but that didn't help (just added music...)

**Comment by roronoa-woe** [comment]
having the same issue. anyone figured out how to fix it?

**Comment by esagos** [comment]
I am having the same problem right now :c
