### ISSUE TITLE
Does not follow system select button configuration

### ISSUE THREAD

**Issue by ticky** [Rinnegatamante/VitaDB-Downloader#50]
Hi there, I just wanted to let you know that VitaDB Downloader doesn't follow the system's circle/cross select button configuration.

I have a Japanese Vita and I personally prefer the Japanese button configuration, but VitaDB Downloader uses the international convention.

This means that while the VitaDB-D GUI itself is using the international convention, the system-provided dialogs VitaDB Downloader uses to confirm actions do not, making it somewhat irritating to use.

It would be nice if VitaDB Downloader followed the system configuration. Thank you!

**Comment by Rinnegatamante** [comment]
Done in v.2.0.

**Comment by CscottT** [comment]
Hi my name is ☆☆CT☆☆ any need for a follow up?
