### ISSUE TITLE
Showing Title ID in Vitadb

### ISSUE THREAD

**Issue by RONIN0095** [Rinnegatamante/VitaDB-Downloader#51]
A small Improvement would be having the Title ID on the left side of the Homebrew where the other Information is written for two reasons

 1. For example, if you use the OneMenu launcher, it sorts the games by their ID, so if you know the ID, it would be easier to find. 2. Some homebrews use the default ID ABCD1234, so you could check if a homebrew uses the same one to ensure it does not replace any of your installed homebrews.

**Comment by Rinnegatamante** [comment]
Done in v.2.0.
