### ISSUE TITLE
Existing Title Id Popup

### ISSUE THREAD

**Issue by RONIN0095** [Rinnegatamante/VitaDB-Downloader#53]
Suggestion: Implement a feature in VitaDB where the app displays a pop-up if another app/game uses the same ID. This would prevent ID collisions.
![Uploading vitadb_downloader_1.7_kubridge.jpg…]()

**Comment by Rinnegatamante** [comment]
TitleIDs for clashing app are now marked in red to distinguish them and a popup will show when attempting to download an app with a clashing titleid.
