### ISSUE TITLE
VitaDB  2.00

### ISSUE THREAD

**Issue by thatboynice** [Rinnegatamante/VitaDB-Downloader#54]
It’s keeps telling me there’s a new update when I’m currently running latest update

**Comment by Rinnegatamante** [comment]
Download the vpk and open it with a zip editor. Extract vdb_daemon.suprx in ux0:data/VitaDB and restart the Vita. That should solve the issue.

A proper fix for this will be delivered on next update.

**Comment by landsman** [comment]
I had this issue as well.

**Comment by thatboynice** [comment]
> Download the vpk and open it with a zip editor. Extract vdb_daemon.suprx in ux0:data/VitaDB and restart the Vita. That should solve the issue.
> 
> A proper fix for this will be delivered on next update.

Thank you it worked!

**Comment by thatboynice** [comment]
> I had this issue as well.

Just follow Rinnegatamante instructions & it will work.

**Comment by landsman** [comment]
> Download the vpk and open it with a zip editor. Extract vdb_daemon.suprx in ux0:data/VitaDB and restart the Vita. That should solve the issue.
> 
> A proper fix for this will be delivered on next update.

Yes, worked.

**Comment by HollywoodYT** [comment]
omg thank god for the fix i wanted to go crazy for an update lol

**Comment by DS-00** [comment]
> Download the vpk and open it with a zip editor. Extract vdb_daemon.suprx in ux0:data/VitaDB and restart the Vita. That should solve the issue.
> 
> A proper fix for this will be delivered on next update.

Fixed the issue for me as well. Thank you 😊

**Comment by Rinnegatamante** [comment]
Fixed in v.2.1
