### ISSUE TITLE
App crashes if the background music file is missing

### ISSUE THREAD

**Issue by thipeto** [Rinnegatamante/VitaDB-Downloader#6]
Hi Rinne, big fan here <3

> v1.2 Fixed a bug causing the app to crash if the background music file was missing.

I had installed the 1.2 vpk, with the libshacccg file inside /ur0/data/

All good, but the VPK still crashes on start. So I downloaded the bg.ogg file and uploaded it to /ux0/data/VitaDB and it worked

So, the bug is still there. Can you double check?

https://github.com/Rinnegatamante/VitaDB-Downloader/releases/download/v.1.2/VitaDB.vpk

**Comment by Rinnegatamante** [comment]
v.1.2 doesn't have this issue. You're likley not on v.1.2.
