### ISSUE TITLE
wrong icon showing on first app in list, after using sort. 

### ISSUE THREAD

**Issue by CatoTheYounger97** [Rinnegatamante/VitaDB-Downloader#7]
After using the sort dropdown, the icon for the top app in the list will show a wrong icon. This wrong icon is that of the previous app at the top of the list, pre sort. Navigating to the second app in the list shows the proper icons.

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/VitaDB-Downloader/commit/62ba9a14c8f0344434a48455ec89518b998b6aeb and will be available on next release.
