### ISSUE TITLE
Wrong file downloaded from VitaDB site

### ISSUE THREAD

**Issue by thipeto** [Rinnegatamante/VitaDB-Downloader#8]
Hi Rinne, me again.

The "Download VPK" button on this page (https://vitadb.rinnegatamante.it/#/info/877) isn't downloading the most recent file (v1.3). Instead, it downloads the v1.1 file:

![rinne](https://user-images.githubusercontent.com/81275215/188948208-e4fd7004-dfef-4eb1-a6ae-d860361951e5.jpg)

That's why I found a bug and opened a request in here, I thought the VitaDB was giving me the most updated file (v1.2 in that moment): https://github.com/Rinnegatamante/VitaDB-Downloader/issues/6

**Comment by thipeto** [comment]
> Hi Rinne, me again.
> 
> The "Download VPK" button on this page (https://vitadb.rinnegatamante.it/#/info/877) isn't downloading the most recent file (v1.3). Instead, it downloads the v1.1 file:
> 
> ![rinne](https://user-images.githubusercontent.com/81275215/188947710-88b1208c-fc65-4930-9b69-35d041162931.jpg)
> 
> That's why I found a bug and opened a request in here, I thought the VitaDB was giving me the most updated file (v1.2 in that moment): #6

**Comment by Rinnegatamante** [comment]
That's a CloudFlare cache issue (it's dependant to your IP). If i download from the same exact button, i get the latest vpk.

**Comment by thipeto** [comment]
Just wanted you to know. The average user will consider it a bug. But that's ok, I do my research to download the latest files.

**Comment by mightysashiman** [comment]
Might there be a an extra checksum check the app can do upon download completion to at least detect such caching issues and warn the user when it occurs?
